### ISSUE TITLE
Stratum spec

### ISSUE THREAD

**Issue by sammy007** [BTCGPU/BTCGPU#37] opened 2017-10-18 13:10 UTC
Since BTCGPU utilises equihash it's wise to follow zcash stratum spec, will make existing miners compatible. https://github.com/str4d/zips/blob/77-zip-stratum/drafts/str4d-stratum/draft1.rst

**Comment by StarbuckBG** [comment] 2017-10-19 07:03
Thanks, this will be done.

**Comment by oliverw** [comment] 2017-10-19 13:20
So the plan is to make BTG a drop-in replacement for ZCash from a pool's/miner's point of view?

**Comment by h4x3rotab** [comment] 2017-10-19 17:56
Confirmed. Existing stratum protocol works well with Bitcoin Gold block format. But some minor changes in pool software are still needed. More specifically, the pool must put the block height in the first 4 bytes of hashReserved field.

Anyone who can list popular pool softwares?

**Comment by oliverw** [comment] 2017-10-19 17:59
> Confirmed. Existing stratum protocol works well with Bitcoin Gold block format. 

Should that read _"existing ZCash stratum protocol"_? The ZCash stratum differs quite a bit from the protocol used by the rest of the Bitcoin Heritage of coins.

**Comment by argos66** [comment] 2017-10-20 05:58
>More specifically, the pool must put the block height in the first 4 bytes of hashReserved field.
> Anyone who can list popular pool softwares?

I use z-nomp that use node-stratum-pool, this pool can be natively compatible ?

If you've made a modification on a pool can you share it ?

**Comment by StarbuckBG** [comment] 2017-10-20 08:49
I will share it with open-source license

**Comment by argos66** [comment] 2017-10-20 09:03
thanks, I'm wait to discover this code and test for be ready when mainet opening.

**Comment by dp-unique** [comment] 2017-10-20 14:53
Will wait for this as well!

**Comment by egyptianbman** [comment] 2017-10-22 07:23
Waiting as well. Also using z-nomp.

**Comment by sammy007** [comment] 2017-10-23 11:00
@StarbuckBG you confirm that stratum is compatible with zcash?

No one actually interested if you will share something or not, I am independent dev and would like to write my own so I need a spec.

**Comment by StarbuckBG** [comment] 2017-10-23 11:06
As an independent developer and intentionally hating person you shall be able to check the code and provide independent solution.

As soon as I finish work on the stratum protocol I will publish the code.

**Comment by sammy007** [comment] 2017-10-23 11:10
You just take zcash stratum and go with it, no need for amateur solutions. Everyone will be thankful, I promise.

**Comment by sammy007** [comment] 2017-10-23 11:12
Hint: because you probably need existing mining software to work with BTCG.

**Comment by StarbuckBG** [comment] 2017-10-23 11:16
Please improve your behaviour as it is completely not professional. I will stop answering all of your questions as all the properties you give to the team and the project are completely irrelevant. 
We are here to provide solutions, not to offence!

**Comment by sammy007** [comment] 2017-10-23 11:23
You are here to scam, you all are not capable to provide solutions. Do not lie to yourself.

**Comment by StarbuckBG** [comment] 2017-10-23 11:38
The coin is on the market in few hours, the fork is tomorrow. 
Lets see.
I cannot understand how you are one of the guys that I liked the work they have made and at the end you are just a spammer blaming us without actual facts, only on assumptions. 
I wish you good luck with your projects and protocols. I hope one day you understand how wrong you are and that this is not good way to talk to other developers.

**Comment by StarbuckBG** [comment] 2017-10-23 11:44
I want you to tell to all the team that is working more than 18 hours a day for the last week, that this is a scam. Tomorrow I will be in the Jimmy Song's show I would definitely have in mind the way you are behaving and that one of the persons that have made that much for the mining society is behaving that way. It is not cool (:

**Comment by sammy007** [comment] 2017-10-23 11:45
You are disturbing 100 billion dollars market. I posted a few concerns, if addressed you can make it smooth for everyone, unfortunately you refuse to listen.

* Make stratum 100% compatible with zcash so coin will inherit existing mining software and pool software.
* Provide a testnet prior launch so if needed we all can make adjustments.

If you are not capable to provide a working testnet I have no idea what does "provide solutions" mean.
I really care not if this a money grab or just school project, but if you claim you are a professional you will address these issues.

I would join slack if it's possible, but I failed yesterday, link is kinda broken.

**Comment by sammy007** [comment] 2017-10-23 11:49
It's still a mistery for me how people are going to launch a bitcoin fork without providing code before launch. Normal launch = post mainnet code 5 minutes before launch so we all can set it up, but there is literally no reason to hold on testnet. You can publish it right now if it's ready. if testnet code is not ready simply don't launch.

I am sure people will agree with e that testnet must go with equihash algo since genesis or block 1. There is no need for legacy. For testing transition you should have a reg test.

**Comment by StarbuckBG** [comment] 2017-10-23 11:50
The incompatibility with Zcash is made for better as even Daira mentioned that they are planning to add the block height as argument for the block calculation.
The testnet is under development. I try to do all my best but most of the time I need to answer such kind of attacks and other problems that developers meet.
We need more devs, not more enemies. We are open to everyone that wants to help us, but when people are attacking us we are left with no other chance than doing everything by ourselves ..

**Comment by sammy007** [comment] 2017-10-23 11:51
So we are waiting for an altered zcash stratum spec for bitcoin gold in order to start development on our side.
We: me and a dozen of pool ops for sure.

**Comment by StarbuckBG** [comment] 2017-10-23 11:52
About the testnet I needed to download the bitcoin testnet in order to check if the change of the PoW is handled and I needed to modify the DNSSeed code. I have done both of the things and have synched all of the testnet. 
The regtest shows no problems with the PoW change. Today I will finishing the stratum protocol and will provide the changes so the mining pools can start.

**Comment by OleksandrBlack** [comment] 2017-10-25 06:11
+1
UP

**Comment by DeadMan993** [comment] 2017-10-28 02:49
When can I add a coin to the pools?

**Comment by TheComputerGenie** [comment] 2017-10-28 12:25
https://github.com/BTCGPU/BTCGPU/issues/37#issuecomment-337987188

> Confirmed. Existing stratum protocol works well with Bitcoin Gold block format. But some minor changes in pool software are still needed. More specifically, the pool must put the block height in the first 4 bytes of hashReserved field.
> 
> Anyone who can list popular pool softwares?

https://github.com/z-classic/z-nomp

**Comment by StarbuckBG** [comment] 2017-10-28 12:58
How you tested the mining process ?
I needed to modify the stratum protocol of z-bono because it didn’t liked the block format.

**Comment by h4x3rotab** [comment] 2017-10-28 13:01
We tried to follow zcash stratum spec but most miners still check the version field and the hashReserved field of the block header. So some changes are still needed for the miner side.

**Comment by sammy007** [comment] 2017-10-28 13:18
So change it, publish markdown with spec, make a fork of CPU miner so devs can catch up.

**Comment by StarbuckBG** [comment] 2017-10-28 13:47
I am already modifying it :) I will publish the spec and the modified nheqminer so the people can start working.

**Comment by sennevb** [comment] 2017-10-29 21:10
Als onot bad to notify claymores and optiminer and so..

**Comment by sammy007** [comment] 2017-10-30 21:22
> the pool must put the block height in the first 4 bytes of hashReserved field.

@h4x3rotab could you publish a diff with zcash format?

**Comment by sammy007** [comment] 2017-10-30 22:04
```
PREVHASH (hex)
The 32-byte hash of the previous block, encoded as in a block header.
MERKLEROOT (hex)
The 32-byte Merkle root of the transactions in this block, encoded as in a block header.
RESERVED (hex)
A 32-byte reserved field, encoded as in a block header. Zero by convention (in hex, 0000000000000000000000000000000000000000000000000000000000000000).
TIME (hex)
The block time suggested by the server, encoded as in a block header.
```

So for block `492407` `RESERVED` instead of 64 char zero hex must be:

```
0007837700000000000000000000000000000000000000000000000000000000
```

Or it must be reversed or something else.

**Comment by StarbuckBG** [comment] 2017-11-01 14:29
https://github.com/poolgold/z-nomp

**Comment by StarbuckBG** [comment] 2017-11-01 14:29
This is working as bitcoin gold pool.

**Comment by DeadMan993** [comment] 2017-11-01 14:55
> This is working as bitcoin gold pool.
Will you need to make a new pool? or can be installed on any z-nomp pool?

**Comment by TheComputerGenie** [comment] 2017-11-01 23:01
@DeadMan993 Because of the stratum edits, merging is best left to qualified pool operators.

**Comment by sammy007** [comment] 2017-11-03 14:16
So we can use block version = 4 now, it will make all existing zcash miners compatible, are you going to require exact version from `getblocktemplate` or `4` will remain acceptable?

**Comment by h4x3rotab** [comment] 2017-11-03 14:21
@sammy007 version=4 is not feasible for Bitcoin Gold because of bip9

**Comment by oliverw** [comment] 2017-11-03 14:21
@sammy007 Out of curiosity, why would you use anything but the version from GBT? Regarding miner compatibility. Wouldn't miner still choke on the block height encoded in the first 4 bytes of hashReserved?

**Comment by sammy007** [comment] 2017-11-03 14:55
@oliverw because there is a note in zcash spec that miners (software) must warn and don't mine other versions, I know at least one miner (nicehash cpu miner) which refused to mine anything but version 4. The `4` is also hardcoded in your znomp fork. If you need to inherit existing miners you should allow it. I have no idea if it works on mainnet, but I had a private testnet and it was acceptable. Can't mine on current live testnet because idiots bumped difficulty.

**Comment by oliverw** [comment] 2017-11-03 14:58
@sammy007 True, I remember that. By the way I've never worked on any znomp forks. I'm working on https://github.com/coinfoundry/miningcore.

**Comment by sammy007** [comment] 2017-11-03 15:01
It was mentioned in this tracker, I don't remember who made it, pardon.

**Comment by oliverw** [comment] 2017-11-03 15:10
@sammy007 No problem. This whole story is pretty chaotic. 

Can anyone recommend a miner compatible with the current BTG testnet?

**Comment by sammy007** [comment] 2017-11-03 15:17
They all must be compatible as long as miner don't give fuck to block version or if at least one fuck given and as long as daemon accepts block version 4.

**Comment by sammy007** [comment] 2017-11-03 15:20
What hash reversed? Any new changes to stratum after testnet went live?

**Comment by oliverw** [comment] 2017-11-03 15:21
https://github.com/StarbuckBG/node-stratum-pool/blob/44d2b721a4164f4763a1b678b8377b50114ecaec/lib/blockTemplate.js#L136

**Comment by sammy007** [comment] 2017-11-03 15:23
I only used nhequiminer and it works. Must work as long as it is not hardcoded in miner.

**Comment by StarbuckBG** [comment] 2017-11-03 15:23
Guys this starts to be more like a chat. Do you want to join BTG slack and to make a group to discuss it and the summarise here ?

**Comment by StarbuckBG** [comment] 2017-11-03 15:24
Use this link - https://join.slack.com/t/bitcoin-gold/shared_invite/enQtMjY1MzkzMzUxNjY4LWM1YmQ4MjZhZTQxMWE1ZDQyNjA4N2QwZTkyZjYzMjhiMzdlMmVkNjQ3NzZlZDdmMDE4NWIyY2JmYzdjYmE2MzA <https://join.slack.com/t/bitcoin-gold/shared_invite/enQtMjY1MzkzMzUxNjY4LWM1YmQ4MjZhZTQxMWE1ZDQyNjA4N2QwZTkyZjYzMjhiMzdlMmVkNjQ3NzZlZDdmMDE4NWIyY2JmYzdjYmE2MzA> 
Find Martin Kuvandzhiev - that is me.

**Comment by sammy007** [comment] 2017-11-03 15:25
I prefer to talk about it in public here, with slack only a few people will learn. Pretty relevant despite its not an exact issue. A stratum diff with zcash will help and miners can contribute to compatibility spreadsheet.

**Comment by StarbuckBG** [comment] 2017-11-03 15:32
Ok!

I will tell you the required changes in nomp and the mining software.

1. The reserved field is having the block height in LSB format in the first 4 bytes. The rest are the same.
2. NHeqminer needed a change in the block version. It was supporting only block version 4, the version of BTG is a lot higher. It is fixed in https://github.com/poolgold/nheqminer <https://github.com/poolgold/nheqminer> 
3. I have made some minor changes on z-nomp and nomp because some of the code was not good at all. 
4. Mining software is accepting the block format from the stratum protocol and no changes are required for EWBF and Claymores miner. 

@sammy007 please mind you language. GitHub is no place for swearing, be business. 

@Oliver please use this repos for already tested software : https://github.com/poolgold <https://github.com/poolgold>

**Closed** 2017-12-13 08:51 UTC

**Comment by shakilmia** [comment] 2017-12-13 09:09
h4x3rotab
