### ISSUE TITLE
Bitcoin Gold Decentralization Problem

### ISSUE THREAD

**Issue by Spicy12** [BTCGPU/BTCGPU#81] opened 2017-10-24 19:58 UTC
How will Bitcoin Gold make Bitcoin Decentralized again? There doesn't seem to be a specific directive or feature that insures that this is the case (other than what already exists in Bitcoin) other than the PoW algorithm.

The mining algorithm is only 1/3 of the problem. The nodes are another 1/3 of the problem. Development is the other 1/3.

To be more decentralized, there should be some incentive to proliferate full nodes as much as possible. Maybe by adding some features that incentivize full nodes, etc.. Not necessarily like the way that dash is setup where full nodes get handouts; but; something that incentivizes users to actually run legitimate full nodes.  

A handful of servers on a few continents isn't decentralized at all. Equihash is much more accessible to average people than SHA256; I'll give you that. What about the development team(s) and the network nodes? Is there a plan to make them more accessible to average people?

**Comment by joebotbr** [comment] 2017-10-24 21:58
What about a decentralized exchange, like Dex (Waves)?

**Comment by brbatv** [comment] 2017-10-24 22:45
he knows too much, suicide him

**Comment by Grimm2017** [comment] 2017-10-25 01:34
Decentralization was just an excuse.  There is nothing else.

**Comment by therealcmilohernandez** [comment] 2017-10-25 03:46
How about paying a percent of transaction fees for running full nodes?

**Comment by StarbuckBG** [comment] 2017-10-25 07:05
Then again some guys can buy 1000 RaspberryPi connect them to an NAS and get most of the money.

**Comment by Thecreator1** [comment] 2017-10-25 08:03
This whole things smells like self enrichment.
For me there is only one Bitcoin and it's BTC so not BCC, nor BTG or BTX.
And your failures will only make it stronger.
What kind of a development team has to put up a bounty in the last several days to get one of the most crucial elements done ? And as many have written, it states on your website multiple times that it **has** been implemented, and any query about changing the content is simply ignored...
That is the opposite of being decentralized, honest and transparent and my guess is that the team is working on other things, like premining for example ?
How can it be that there are already two exchanges trading BTG, when there is no possibility to deposit/withdraw wallets?
These also must be fake price feeds, i saw price drop down almost 25$, in a crash like fashion.
But not any lower... Of course the 'market makers' have to keep the thing going and therefore they will not allow price to drop too far down, because then the instrument will simply disappear and they will have nothing left to offer, so that people can buy it and then they can artificially slam it down again, stripping whoever bought it from their capital.
This is called 'simulated reality' and it is a place you better stay far far away from.
And it has got nothing to do with Blockchain Technology, none of the transactions are logged on a blockchain! Those people buying BTG are just poor souls who do not understand the technology and they are being preyed on and robbed...
So hiding behind decentralization, while lying and trying to enrich yourselves behind the scenes, as you can see wont stand a chance against the real Bitcoin blockchain.
The one that has absorbed the impact from your 'team's' endeavors yesterday, and is already back up and climbing again.
So we have seen what the caused uncertainty does to the market, and what doesn't kill it will make it stronger.
Thank you for brake testing Bitcoin.
It has successfully passed the test.
Obviously your system hasn't.
Why would the founder be the owner of the company that is selling ASIC's ?
He would sabotage his own equipment this way.
I bet he is not planning to go sell GPU's or is it ?
I knew something was up from the start.
I have read that you are only in for the past two weeks... maybe there are things that you don't know.
Maybe it was all designed to collapse like this... and you are defending something that is not what you think it is.
Question Everything.

**Comment by StarbuckBG** [comment] 2017-10-25 10:46
This is not a topic for GitHub. You can join Slack and discuss there.
I will close this issue. More information can be found on BTG FAQ: https://btcgpu.org/faq/ and the roadmap: https://btcgpu.org/wp-content/uploads/2017/10/BitcoinGold-Roadmap.pdf
For discussion you shall use Slack: https://join.slack.com/t/bitcoin-gold/shared_invite/enQtMjYxMDU5NzQzNjUyLTJlODRhYjg2NGRmMzE4ZjBkZjlmOGM0ZDc0OGUyMDZmMTVlY2RjZDc2OWQ0NWY2NWI0ODcyZjYwZTVhMjQ5OTE

**Closed by StarbuckBG** 2017-10-25 10:46 UTC

**Comment by joebotbr** [comment] 2017-10-25 11:39
"Then again some guys can buy 1000 RaspberryPi connect them to an NAS and get most of the money."

But ALL exchanges can get money from this "decentralized" bitcoin.

**Comment by mjoh090** [comment] 2017-10-26 23:10
@Thecreator1 @bilbobits raises an interesting suspicion in his post here - https://github.com/BTCGPU/BTCGPU/issues/89#issuecomment-339555307

"..note the CHINESE just brought in this EURO programmer Proffessor 'starbuck' two weeks ago prior to this BTG had been a poorly orchestrated ICO since August, about when they got 'banned' in China, which is probably why this puppy got re-packaged as a minable gpu coin."

**Comment by StarbuckBG** [comment] 2017-10-27 07:31
@mjoh090 please refer with facts to prove that the words that you have said are truth.
Moreover I’m in this projects from 13.10.2017 . Do not stamp my name everywhere without facts!

**Comment by mjoh090** [comment] 2017-10-27 09:05
@StarbuckBG I clearly stated that it was a suspicion raised by @Bilbobits. The aspect that references you may, or may not have been accurate. This comment made by Bilbobits was made yesterday, and you have just confirmed the accuracy of my quoting it today, since 13.10.2017 is exactly two weeks ago. Just so you know, Bilibobits comment that references you was really about Jack.

**Comment by mjoh090** [comment] 2017-10-27 09:36
@StarbuckBG You indicate that you arrived very recently to the project (2 weeks ago) with the implication that you inherited the problems associated with the launch of BCTGPU. 

OK I can accept that, but my displeasure has been with the decision to privately premine for reasons that I have made clear elsewhere. 

So here is context and opportunity for you to clarify your involvement in that decision by answering an this question regarding the private premine of the chain- Did you vote for it, and if so, what is your position now on the wisdom of that decision?
