### ISSUE TITLE
Exact method of fork

### ISSUE THREAD

**Issue by ronaldobini** [BTCGPU/BTCGPU#56] opened 2017-10-21 13:42 UTC
There is great discussion about how will the fork be done. You guys already have a exact block to execute the snapshot. But when exactly?

In the very second that the block is found? Or at the end of the period of this block?

**Comment by h4x3rotab** [comment] 2017-10-21 21:14
From block 491407, new consensus rules will be enforced by Bitcoin Gold full nodes. However block 491406 is still valid in both chains.

**Comment by leto** [comment] 2017-10-22 04:15
Another way to say this, to try and clear things up, is this:

Bitcoin and Bitcoin Gold blockchains are exactly the same from genesis block to block 491407. Block 491408 is the first "Bitcoin Gold" block, that is where the blockchains diverge. The will share about a half million blocks of shared transaction history (around 110GB on disk) and then the blockchains will become divergent, i.e. block 491408 on the Bitcoin blockchain will have nothing to do with block 491408 on the Bitcoin Gold blockchain. They will be completely different coins. I hope that helps clear up the method of fork.

**Comment by egyptianbman** [comment] 2017-10-22 07:25
Is there any way to "pre download" the blockchain? Sorry if this sounds noobish but I'm wondering how I can get this coin up and running in my pool as soon as the network is live.

**Comment by krtschmr** [comment] 2017-10-22 09:17
@egyptianbman can't you just sync the BTC node and then take the raw files and throw them into btcg node?

**Comment by StarbuckBG** [comment] 2017-10-22 09:26
There will be version mismatch. You must do it from
Our core.

**Comment by ronaldobini** [comment] 2017-10-22 17:50
So until when exactly I have to keep my bitcoin to then receive btg in the other chain? Until the end of the block 491406?

**Comment by TBomberman** [comment] 2017-10-22 18:50
There is a premine of 8000 blocks by an "insider" group. When the block reaches 491407, BTC will automatically move up 8000 blocks to 499407, the coins mined from the 8000 blocks all belong to the inside group of btg seed nodes. That is about 200,000 coins. In a fork like BCC where the value is $300 per coin, that is equivalent to about $60m usd. This all goes to the insider group. Seems to be a very nice reward. Please correct me if I am wrong.

**Comment by D3m0nKingx** [comment] 2017-10-22 19:00
Don't forget BCC also pumped to 900$ or so...

**Comment by TBomberman** [comment] 2017-10-22 19:04
I question why this is not an open premine group, sounds greedy to me.

**Comment by D3m0nKingx** [comment] 2017-10-22 19:06
It is greed..period.., but the opportunity to make smth off this on a potential pump is the upside for the rest of the community.

**Comment by krtschmr** [comment] 2017-10-23 04:08
the issue is that they premine on DIFF=1 which takes maybe 5 hours time....

**Comment by StarbuckBG** [comment] 2017-10-25 10:40
I will close this issue. More information can be found on BTG FAQ: https://btcgpu.org/faq/ and the roadmap: https://btcgpu.org/wp-content/uploads/2017/10/BitcoinGold-Roadmap.pdf

**Closed** 2017-10-25 10:40 UTC
