### ISSUE TITLE
The problem of late confirmation of coin

### ISSUE THREAD

**Issue by ms500912** [BTCGPU/BTCGPU#209] opened 2017-11-18 12:28 UTC
The Suprnova is being used and the coin is delayed.

Is this a network problem? Or is it a matter of coin itself?

I guess it's not a pool problem.

**Comment by h4x3rotab** [comment] 2017-11-18 12:55
The stuck transactions are mostly SegWit tx.

Here is an experiment. Call `getblocktemplate` without segwit enabled:
```
~/btc/release/bin# ./bgold-cli getblocktemplate | grep 9f5706f43db3fabfdd116057a1440b73123ca22561d32988e0cf2271160ac2b8
```

Call `getblocktemplate` with segwit enabled:
```
~/btc/release/bin# ./bgold-cli getblocktemplate '{"rules": ["segwit"]}' | grep 9f5706f43db3fabfdd116057a1440b73123ca22561d32988e0cf2271160ac2b8
      "txid": "9f5706f43db3fabfdd116057a1440b73123ca22561d32988e0cf2271160ac2b8",
```

Pool.gold's znomp based pools should handle SegWit properly but I doubt if suprnova can handle it correctly.

**Comment by ocminer** [comment] 2017-11-18 14:14
For performance reasons usually segwit is only called/switched on when the blocksize is above a certain limit. Since the blocks on BTCGPU are mostly empty, it was never triggered/enabled from my side. I'll lower the limit and do some testing.

**Comment by StarbuckBG** [comment] 2017-11-18 15:00
I will give detailed instructions how to implement it when I get home.

**Comment by ocminer** [comment] 2017-11-18 15:06
Thanks Martin, I appreciate but I have everything in place already, it was simply not turned on because of the small blocksize :) It's on now and I'm testing.

**Comment by StarbuckBG** [comment] 2017-11-18 15:23
Blocksize is not a problem. I have tested SegWit transactions from the pool in the beginning of the testnet. I have made and mined 3 SegWit transactions.

**Comment by ocminer** [comment] 2017-11-18 15:32
There's a check in my code.. Literally a switch (on/off) that only enables when blocksize reaches a certain limit. This was preventing the activation of segwit here. I've disabled this check now.

**Comment by h4x3rotab** [comment] 2017-11-18 15:55
@ocminer SegWit should be always turned on because even if the block size is not so hight, there are always people trying to send SegWit tx. Pool must support that.

**Comment by ocminer** [comment] 2017-11-18 16:20
What I must and what not is written on a different piece of paper. First I must test things to see if they work or not. Consider this issue fixed.

**Comment by h4x3rotab** [comment] 2017-11-18 16:31
Thank you. We can provide any support if needed. Please keep in touch and feel free to ask us any question.

**Comment by StarbuckBG** [comment] 2017-11-18 16:59
I will reopen the ticket with explanation how to add SegWit support.

**Comment by StarbuckBG** [comment] 2017-11-18 17:11
To all pools: In order to add SegWit support you need to do the following changes:

1. On get block template, you must add parameter "rules": [ "segwit" ]. References:
- https://github.com/StarbuckBG/node-stratum-pool/blob/6cce4b3eeb2e4f5dff2c9c2e2daf2f5ae2fede60/lib/pool.js#L125
- https://github.com/StarbuckBG/node-stratum-pool/blob/6cce4b3eeb2e4f5dff2c9c2e2daf2f5ae2fede60/lib/pool.js#L578

2. You need to add the TXID field in the merkle tree calculation instead of HASH in order to provide the correct tree. Reference:
- https://github.com/StarbuckBG/node-stratum-pool/blob/6cce4b3eeb2e4f5dff2c9c2e2daf2f5ae2fede60/lib/merkleTree.js#L16

3. Add 0 value transaction to the witness address on finding the block if there is a witness field on the getblocktemplate:
- https://github.com/StarbuckBG/node-stratum-pool/blob/09e46f7e025317b39d7b2b99484a3ff6cd611a96/lib/transactions.js#L80 

If you have any questions, please post them here.

**Comment by charleshugh84** [comment] 2017-11-18 17:28
How is this possible - Suprnova.cc to limit SegWit transactions, because they wanted to? This is a fkn censorship to the network and the transactions. This is absolutely unprofessional! WTF for real ? And you requested to close this issue to put down the fire ??? I cannot believe this. And you call your pool professional? Only excuses from you ........

HOW IT IS POSSIBLE TO CENSOR THE NETWORK THAT WAY SUPRNOVA???


PS. Respect to that lad, after all the hate you gave him, he still tries to help all of you. You don't deserve it.

**Comment by ocminer** [comment] 2017-11-18 17:30
whats wrong with you ? censorship ?! transactions are still going through, this is a new coin and things need to be tested. there was no testnet where segwit tx'es could be tested so it was initially turned off so no funds/txes get lost on mainnet.. as it's now needed it's getting enabled. period.

**Comment by StarbuckBG** [comment] 2017-11-18 17:36
@charleshugh84 take it easy!
@ocminer actually segwit was tested on the testnet foe 7 days at least the BTG team with a major wallet provider has made over 50 segwit transactions. However just post when you are ready.

**Comment by ocminer** [comment] 2017-11-18 17:37
As said already, it's enabled now on the testhost, just waiting for a block to be found.

**Comment by h4x3rotab** [comment] 2017-11-18 17:39
I'm going to delete all the non-technical related messages. Don't abuse GitHub issue and spread hate here.

**Comment by charleshugh84** [comment] 2017-11-18 17:43
You have been finding blocks for 6 days and you didn't noticed that the segwit transactions are not working ??? Are you serious suprnova ??? You have 80% of the network hashrate, do you know how many transactions waited for hours because of your incompetent pool ???

**Comment by shakilmia** [comment] 2017-11-18 17:49
sorry actually i m very busy now

**Comment by ocminer** [comment] 2017-11-18 18:04
@charleshugh84 I don't see that any productive conversation will happen with you so I won't answer on your post. My first priority are the miners on the pool, they need to have a decent, reliable working pool and all "new features" are coming afterwards. There were enough things to work out during launch and nobody even noticed that segwit wasn't working until now, however, it's saturday evening and i'm testing & enabling so what more can you do ?

**Comment by OverSoft** [comment] 2017-11-18 18:11
@ocminer Thanks for your work. Shit happens and some things can't be tested until it's actually live.

**Comment by charleshugh84** [comment] 2017-11-18 18:12
@ocminer your first priority was to make money! It should have been to make a pool that is utilising the whole capabilities of the network. You have made a non-completely functional pool, you have taken 80% of the traffic and then we started to blame bitcoin gold for the slow transactions. At the end it was you guilty of that, because you have LIMITED all SegWit transactions.

**Comment by gappie** [comment] 2017-11-18 18:27
Tick Tock

**Comment by gappie** [comment] 2017-11-18 18:47
@ocminer Do you have an ETA? How many minutes?

**Comment by ocminer** [comment] 2017-11-18 18:53
It's implemented already. However that doesn't speed up confirmations nor block times. It's just a different way to send transactions

**Comment by OverSoft** [comment] 2017-11-18 18:54
If the miners didn't pick up Segwit transactions and now they do, it definitely makes a difference in confirmations and transaction speed.

**Comment by charleshugh84** [comment] 2017-11-18 18:56
When you have 80% of the network hash rate you are responsible for the network as well! Check how many people are waiting for their transactions, because you have decided not to add this code!

**Comment by charleshugh84** [comment] 2017-11-18 18:58
It is not fair to anyone on this network. You make the money and don't care about the people that are actually making transactions in the network .....

**Comment by OverSoft** [comment] 2017-11-18 19:03
@charleshugh84 Nobody is holding you back from mining yourself... If you don't agree, open your own mining pool and start mining on your terms. No reason to go around slinging accusations...

**Comment by charleshugh84** [comment] 2017-11-18 19:07
Opening a pool is not a solution because I'm never going to have that hash rate. We create wallets, we have been digging into this issue for 3 days and lost so many dev hours! This is why I'm mad!

**Comment by b0rgg** [comment] 2017-11-18 19:11
Do we have ETA on when one can expect segwit transactions to be mined?

**Comment by ocminer** [comment] 2017-11-18 19:22
It's active since Martin reported it

**Comment by OverSoft** [comment] 2017-11-18 19:23
There are still no SW transactions going through, so something is still wrong.

**Comment by b0rgg** [comment] 2017-11-18 19:24
So stuck (0) transactions need to be redone?

**Comment by charleshugh84** [comment] 2017-11-18 19:25
none of the sent transactions are executed. 10+ blocks have been found.

**Comment by ocminer** [comment] 2017-11-18 19:26
No, usually they should be picked up automatically

**Comment by OverSoft** [comment] 2017-11-18 19:27
But they're not.

**Comment by b0rgg** [comment] 2017-11-18 19:28
TX are still not being confirmed. Segeit transaction from x hours ago

**Comment by StarbuckBG** [comment] 2017-11-18 19:29
@ocminer if everything is ok they are picked. At least on the z-nomp based pools. Give some more details ?

**Comment by ocminer** [comment] 2017-11-18 19:34
Hmm, everything looks perfect from my side.. I can't see any issue... I'll check again

**Comment by b0rgg** [comment] 2017-11-18 19:34
http://btgexp.com/tx/4902ec6814fe7b448cec2135c9b89da58853daba1c725b71d38e30d67ae3bf8b
Nope, still the same

**Comment by OverSoft** [comment] 2017-11-18 19:35
The issues are perfectly visible client side. ;)
No SW TX's are going thru.

**Comment by charleshugh84** [comment] 2017-11-18 19:36
Unbelievable ....................... This is how a decentralised cryptocurrency becomes centralised and dependent on one mining pool ......

**Comment by ocminer** [comment] 2017-11-18 19:37
This block 0000000007debd20e3485b7d8f062cd816c16f409773936a763523bfd2b40fb6 has lots of TX according to the wallet, but none according to the block explorer..

**Comment by OverSoft** [comment] 2017-11-18 19:37
It has a lot of TX's, but NO segwit transactions.

**Comment by sennevb** [comment] 2017-11-18 19:40
maybe explorer doesnt support the segwit tx yet?? bcuz you cant see them

**Comment by OverSoft** [comment] 2017-11-18 19:42
@sennevb No, because smaller pools are mining SW tx's, and they get through just fine. But because SuperNova is so big, almost no blocks are being found with SW tx's.
It's definitely a SN problem.

**Comment by b0rgg** [comment] 2017-11-18 19:42
ledger wallet shows 0 confirmations for segwit tx

**Comment by ocminer** [comment] 2017-11-18 19:43
I'm checking

**Comment by sennevb** [comment] 2017-11-18 19:43
@OverSoft so for other pools they appear in block explorer?? if yes, then its indeed still a problem..

**Comment by khelle** [comment] 2017-11-18 19:44
It seems the segwit transaction started to be processes. All the segwit tx I had with 0 confirmations are already at least 1.

**Comment by OverSoft** [comment] 2017-11-18 19:45
@sennevb Yes, last SW transactions that went through we're just before 5:00 GMT early this morning. Everything after that did not contain SW tx's.

@ocminer That first block with the SW tx's will be a very nice block from a fee standpoint. ;)

@khelle Not for me. All my tx's are still at 0.

**Comment by b0rgg** [comment] 2017-11-18 19:46
@khelle are you for real? 
ledger segwit wallet showing 0
http://btgexp.com/tx/4902ec6814fe7b448cec2135c9b89da58853daba1c725b71d38e30d67ae3bf8b showing 0

**Comment by LitecoinTim** [comment] 2017-11-18 19:46
I do see some A (SegWit) addresses... https://btg-bitcore2.trezor.io/block/0000000007debd20e3485b7d8f062cd816c16f409773936a763523bfd2b40fb6

**Comment by charleshugh84** [comment] 2017-11-18 19:48
Yes. The first transaction was mined 2 days ago with 9 hours of delay. Today we have made another one, still nothing.

**Comment by ocminer** [comment] 2017-11-18 19:50
Ok cool, thanks for the patience guys

**Comment by OverSoft** [comment] 2017-11-18 19:51
Oops, sorry, looking at the wrong TX ID. Still not confirmed, but i'll check in the next few blocks.

**Comment by b0rgg** [comment] 2017-11-18 19:53
mine still not confirmed as well
@OverSoft you had us CTRL+R for a second there hahah

**Comment by OverSoft** [comment] 2017-11-18 19:54
@b0rgg Sorry, have so many block explorers open right now, i had a block tx instead of my own tx... Oops.

**Comment by b0rgg** [comment] 2017-11-18 19:59
who knows if this is in purpose to prevent people from dumping on hitbtc or changelly...

**Comment by charleshugh84** [comment] 2017-11-18 20:00
Still nothing here.

**Comment by OverSoft** [comment] 2017-11-18 20:01
I think 6 days of segwit transactions need to be caught up. Give it a few hours.

**Comment by b0rgg** [comment] 2017-11-18 20:06
@OverSoft blocks are empty, what are you talking about?


                                                   Transactions |
500655 | Nov 18, 2017 8:49:13 PM | 65 |   | 32860
500654 | Nov 18, 2017 8:40:42 PM | 37 |   | 36819
500653 | Nov 18, 2017 8:31:21 PM | 286 |   | 186825
500652 | Nov 18, 2017 8:07:45 PM | 69 |   | 67387
500651 | Nov 18, 2017 7:51:50 PM | 2 |   | 1855
500650 | Nov 18, 2017 7:51:36 PM | 18 |   | 7370
500649 | Nov 18, 2017 7:47:03 PM | 105 |   | 74394
500648 | Nov 18, 2017 7:22:28 PM | 62 |   | 42853
500647 | Nov 18, 2017 7:09:15 PM | 41 |   | 35374
500646 | Nov 18, 2017 6:56:06 PM | 103 |   | 54168
500645 | Nov 18, 2017 6:35:10 PM | 2 |   | 1856
500644 | Nov 18, 2017 6:33:52 PM | 5 |   | 3346
500643 | Nov 18, 2017 6:33:03 PM | 6 |   | 2653
500642 | Nov 18, 2017 6:31:23 PM | 34 |   | 13601

**Comment by OverSoft** [comment] 2017-11-18 20:07
Yeah, see my edit. ;)
There's still a lot of stuff wrong here...

**Comment by b0rgg** [comment] 2017-11-18 20:09
yeah yeah, sorry
hashing of the blocks does not make any difference if the blocks are 10 transactions or if they are full..that is same speed and, i hardly think that (cuz no way to see the mempool), that next block or two, if it were full, that it would clear out the mempool

do we stats of the mempool?

**Comment by b0rgg** [comment] 2017-11-18 20:10
off the topic, does anyone know if trezor came out with split options or are they taking it easy over the weekend?

**Comment by StarbuckBG** [comment] 2017-11-18 20:11
https://blog.trezor.io/trezor-statement-on-bitcoin-gold-fork-78cebc0532c7 <https://blog.trezor.io/trezor-statement-on-bitcoin-gold-fork-78cebc0532c7>

**Comment by b0rgg** [comment] 2017-11-18 20:15
confirmed!

**Comment by ocminer** [comment] 2017-11-18 20:20
on all my daemons the segwit queue is empty now

**Comment by OverSoft** [comment] 2017-11-18 20:20
Yup, confirmed for me too now. Thanks @ocminer!

**Comment by h4x3rotab** [comment] 2017-11-18 21:05
I'm glad it's finally solved. Time to close the issue.

**Closed by h4x3rotab** 2017-11-18 21:05 UTC

**Comment by charleshugh84** [comment] 2017-11-18 21:37
Thanks!
