### ISSUE TITLE
Importing Wallet

### ISSUE THREAD

**Issue by khelle** [BTCGPU/BTCGPU#204] opened 2017-11-17 14:50 UTC
What is the easiest way to import bitcoin core wallet into btg core to claim ownership of the funds that were on this addresses during the fork? Copying wallet.dat file does not work. Do I have to importprivkey secret for each address?

**Comment by h4x3rotab** [comment] 2017-11-17 14:57
It's reported that copying the wallet.dat and then `-rescan` doesn't work. But it's confirmed that importing the private key works. Will look at this soon.

**Comment by khelle** [comment] 2017-11-17 15:17
Seems "copying" wallet via using RPC method of `dumpwallet` on BTC core and `importwallet` on BTG core works. It generated gold-format addresses for each private key.

Still, I have another problem with that - after doing so, and running `rescan`, I still have balance equal to zero, while it should be much more. What's more the node currently is on block "333629" while I see in https://btgexplorer.com/ the highest is "183087". What is the top block now? Does the "183087" in explorer means, the amoutn of additional blocks since fork, but the node gives me real number? Should I be worried?

**Comment by srg777** [comment] 2017-11-17 16:20
In my case "rescan" didn't work at all
just freeze with 1% progress

**Comment by miranos** [comment] 2017-11-17 17:40
I have problem importing private keys on my wallet !

Using the command ` importprivkey`, each time i launch it, btgold crash !

Any one have same problem ?

The second problem is that i launched `bgoldd -bootstrap` from 5 days now and still 52 GO downloaded actually only ! (Any fix ?).

**Comment by h4x3rotab** [comment] 2017-11-18 06:24
@khelle Neither 333629 nor 183087 is the correct block height. Without a fully synced blockchain your balance will not be accurate. Here are two working explorers: http://btgexp.com, http://btgblocks.com

@srg777 Rescan takes a long time because it will go through the entire blockchain.

@miranos Maybe it's better to use our bootstrap torrent file. It contains the blockchain up to block 500060: https://bitcoingold.org/downloads/

**Comment by srg777** [comment] 2017-11-18 06:33
@h4x3rotab, I got it. but, the very first % take much more time than the rest - and it confuses, when rescanning stucks. please make some disclamer or change the algo of percentage calculation

**Comment by miranos** [comment] 2017-11-18 16:44
@h4x3rotab Where i can put it please ? i have to download extracted files since i have 200 GO on my server.

**Comment by wilsonmeier** [comment] 2017-12-09 20:11
@khelle is the problem solved? If so, please close this issue. Thank you.

**Comment by shakilmia** [comment] 2017-12-09 20:20
@khelle

**Comment by h4x3rotab** [comment] 2017-12-13 09:13
If you find something wrong when importing the wallet (it shows Bitcoin transaction which doesn't exist in BTG blockchain), please use `-zapwallettxes=1` and `-rescan=1` together to refresh the tx history.

**Closed by h4x3rotab** 2017-12-13 09:13 UTC
