### ISSUE TITLE
Is it scam?

### ISSUE THREAD

**Issue by John1231983** [BTCGPU/BTCGPU#73] opened 2017-10-24 08:25 UTC
- Firstly, the website https://btcgpu.org/ is down at 8:22 UTC.
- Secondly, the BTCGPU reported (has implemented) three main features in comparison with BTC and BCH. But these features are not working now. 
- Thirdly, the fork time is changed, the developers are not strong enough, someone just joins the project 2 weeks ago.

From these points, I sure that this fork is just scam.

**Comment by StarbuckBG** [comment] 2017-10-24 08:28
Hello!

It is not a spam. Again Massive DDoS attacks. The cloud provider are helping with improving the network. 10M requests per minute …..
Someone is paying a lot to turn the site down.

**Comment by John1231983** [comment] 2017-10-24 08:31
How about the second and third points? Why do they report three features but nothing is working now?

**Comment by StarbuckBG** [comment] 2017-10-24 08:36
2. PoW is implemented and working fine, block time calculated on each block is ready. Specific addresses and Magic are 99% ready, testnet was started today for a short time and running fine. Minor changes applied it will be back again very soon. Replay protection is WIP.
3. Fork time was based on block not on time. Tipicaly block time is 10 minutes. This time it was a lot faster.

**Comment by boehla** [comment] 2017-10-24 09:47
DDoS? Really?
It give me: 403 Forbidden
Doesn't look like overload...

**Comment by StarbuckBG** [comment] 2017-10-24 10:08
FFS guys what you do on DDoS

**Comment by Rob--** [comment] 2017-10-24 10:35
@StarbuckBG why did your website state that replay protection had already been implemented when that was in fact false? Do you realise that lying on your website does not make this project look reputable?

Secondly, you are giving bounties to people to implement replay protection and develop the test/main net. How can this project possible continue if you don't have a team capable of developing this fork?

**Comment by DarthJahus** [comment] 2017-10-24 11:44
What is the official Bitcoin Gold Twitter account? [@BTCGPU](https://twitter.com/BTCGPU) ?

**Comment by Rob--** [comment] 2017-10-24 11:50
Of course @StarbuckBG won't reply. Says everything about this project.

@DarthJahus that is a scam account with a link to a scam website. They require your BTC private key.

**Comment by StarbuckBG** [comment] 2017-10-24 11:51
Guys, you are asking inadequate questions here. Use the Slack.
We are currently under serious DDoS attack. Someone has paid too much for this ……
official twitter is @bitcoingold

**Comment by StarbuckBG** [comment] 2017-10-24 11:52
And as I said, better stop the hate and do something productive. When you have github it means that you at least can read some code.
We will be happy to have at least a bit more support on that.
We are just 2 developers and all the world are asking question 24/7.
I lose 4 hours a day to answer questions anywhere and more 12 hours to work on this.

**Comment by Rob--** [comment] 2017-10-24 11:55
The Slack link no longer works. And you have not answered my question, why have you lied to everyone about the replay protection? If you actually answered any of the questions, people would stop asking questions. You do not lose 4 hours a day because you aren't answering any questions...

**Comment by DarthJahus** [comment] 2017-10-24 12:00
Okay, guys. Let's calm everything down.

* Replay protection is WIP as pointed out by the Trello pannel;
* The website can be under DDoS;
* The Slack invitation link may be broken.

Let's give them some time and see how things go. Time will answer all our questions.

**Comment by D3m0nKingx** [comment] 2017-10-24 12:02
Exchanges are trading live now https://twitter.com/bitcoingold/status/922793556598771713

let it go! stop misusing github for non-code contributions! use the proper channels!

**Comment by Rob--** [comment] 2017-10-24 12:04
The problem is that the website stated that replay protection had already been fully implemented. This is a lie and makes Bitcoin Gold look like a scam. No one is addressing this and @StarbuckBG is avoiding every single question.

Exchanges are trading when the main/test net hasn't even been developed. Bitcoin Gold is worth $0 right now.

**Comment by DarthJahus** [comment] 2017-10-24 12:05
@D3m0nKingx,

> stop misusing github for non-code contributions!

We know that some exchanges opened BTG trades (yesterday, for YoBit). But without a proper functionning wallet, there will be no withdrawal, no value and no Bitcoin Gold (as @Rob-- pointed out). And a proper wallet / network is a question related to the code.

Again, let's just wait and not hurry the devs.

**Comment by StarbuckBG** [comment] 2017-10-24 12:08
Slack: https://join.slack.com/t/bitcoin-gold/shared_invite/enQtMjYxMDU5NzQzNjUyLTJlODRhYjg2NGRmMzE4ZjBkZjlmOGM0ZDc0OGUyMDZmMTVlY2RjZDc2OWQ0NWY2NWI0ODcyZjYwZTVhMjQ5OTE <https://join.slack.com/t/bitcoin-gold/shared_invite/enQtMjYxMDU5NzQzNjUyLTJlODRhYjg2NGRmMzE4ZjBkZjlmOGM0ZDc0OGUyMDZmMTVlY2RjZDc2OWQ0NWY2NWI0ODcyZjYwZTVhMjQ5OTE>

**Comment by bit79** [comment] 2017-10-24 16:04
How can the website be under DDOS if it is behind Cloudflare? I thought Cloudflare was the antidote to DDOS attacks. Just asking?

**Comment by StarbuckBG** [comment] 2017-10-24 16:05
We were penetrated though forgotten resource pointing the the IP address because of a dependency in the site. I have listed the resource in the dev chat.

**Comment by bit79** [comment] 2017-10-24 16:09
Thank you for the answer. I do not know if it helps, but you can probably whitelist Cloudflare's IP addresses in your firewall in order to resolve the situation. (https://www.cloudflare.com/ips/) Or change your web server's IP address and update Cloudflare. Good luck!

**Comment by StarbuckBG** [comment] 2017-10-24 16:54
That was one of the options but I have decided to end this and make a replication of the main site and add Nginx load balancer in front to blacklist the attackers (if there are any) and to switch between the machines. The providers are doing that right now.

**Comment by axvm** [comment] 2017-10-24 17:04
looks like u just focked up. again. gl in development

**Comment by mmouse-** [comment] 2017-10-24 17:08
This is certainly the shittiest shitcoin launch I've seen for quite a while.  
No wallet binaries, no working sourcecode, no real exchanges (besides some which are trading IOUs for made-up prices), no working website. Congratulations to the new Bitcoin *LMAO*

**Comment by leto** [comment] 2017-10-24 17:20
@StarbuckBG to clarify, have you removed CloudFlare or are you changing the configuration of it?

**Comment by DarthJahus** [comment] 2017-10-24 18:10
@leto, according to https://btcgpu.org/, CloudFlare is still there, and was there this morning when the site was giving HTTP 403 error.

**Comment by adhood** [comment] 2017-10-24 18:50
**BITCOIN GOLD HAS NOT LAUNCHED YET!**

The countdown on the website was ONLY for the snapshot of the Bitcoin blockchain.

Everyone who is crying "scam" expected this fork to be just like the Bitcoin Cash fork, where the snapshot and launch occurred simultaneously. This is not the case with Bitcoin Gold. The only thing that happened so far is the snapshot has been made. Now it's time to start working on the actual product, wallets, documentation, etc. It's all still in very early stages of development.

**There is no scam.** If you held Bitcoin at the time of the snapshot then you have already received your Bitcoin Gold. You just can't do anything with it until Bitcoin Gold actually launches.

**Comment by D3m0nKingx** [comment] 2017-10-24 18:52
You can sell it lol

**Comment by StarbuckBG** [comment] 2017-10-24 20:57
We still have cloud flare, but we have also added a load balancer after CF. 
Then we have 2 powerful servers and 2 that are just in case.
Site is ready for DDoS :D

**Comment by lra** [comment] 2017-10-24 21:44
> Everyone who is crying "scam" expected this fork to be just like the Bitcoin Cash fork, where the snapshot and launch occurred simultaneously. This is not the case with Bitcoin Gold.

This can't be the case for Bitcoin Gold because you need to pre-mine your own 20% coins.

I'll let people understand what it means.

**Comment by joebotbr** [comment] 2017-10-24 22:06
The team looks more concerned about the website than the codes. You've done a good job with the website. Have you ever thought about abandoning this project and working only with website development and webhosting?

**Comment by DarthJahus** [comment] 2017-10-24 23:40
> The team looks more concerned about the website than the codes. You've done a good job with the website.

They certainly need to save appearances and calm down people who call for scam "because" the website is down. Once this fixed, and once people refocus to the code and start screaming "scam" because the wallet isn't compiling correctlu, then the devs will also focus on the code 🗡 😆  Don't take this too seriously. People need time and they still have 6 days or so before the Armagedon.

**Comment by StarbuckBG** [comment] 2017-10-25 10:43
I will close this issue. More information can be found on BTG FAQ: https://btcgpu.org/faq/ and the roadmap: https://btcgpu.org/wp-content/uploads/2017/10/BitcoinGold-Roadmap.pdf
For discussion you shall use Slack: https://join.slack.com/t/bitcoin-gold/shared_invite/enQtMjYxMDU5NzQzNjUyLTJlODRhYjg2NGRmMzE4ZjBkZjlmOGM0ZDc0OGUyMDZmMTVlY2RjZDc2OWQ0NWY2NWI0ODcyZjYwZTVhMjQ5OTE

**Comment by StarbuckBG** [comment] 2017-10-25 10:43
The team is available for all the questions you have on our Slack.

**Closed by StarbuckBG** 2017-10-25 10:43 UTC

**Comment by StarSmasher44** [comment] 2017-10-25 12:08
Whats with the everexpanding amount of pre-mined coins?

**Comment by DarthJahus** [comment] 2017-10-25 17:11
@StarSmasher44, can you develop what you are talking about?
