### ISSUE TITLE
Replay Protection Implementation

### ISSUE THREAD

**Issue by StarbuckBG** [BTCGPU/BTCGPU#51] opened 2017-10-20 17:44 UTC
**Two-way replay protection must be provided in Bitcoin Gold**
Refer to #18

**The solution must feature**:
- two-way SIGHASH_FORK_ID replay protection
- clean and readable code
- automated tests

**Bounty: 250 BTG** 
**Bonus 50 BTG if the task is finished before 25.10.2017 12:00 UTC**

**Comment by vattay** [comment] 2017-10-20 19:35
I'll take a stab at this, even though someone with more BTC experience will probably stomp me. Building project now.

**Comment by h4x3rotab** [comment] 2017-10-20 19:47
Great! We also have one person working on this and maybe we can collaborate to speed up the progress. (All the bounty belongs to you.)

**Comment by vattay** [comment] 2017-10-20 19:50
Collab == good. I'm on Bitcoin Gold slack as LxF77.

**Comment by drewdotpro** [comment] 2017-10-20 19:59
I thought this was a "work in progress" for the last 2+ weeks?
https://github.com/BTCGPU/BTCGPU/issues/18#issuecomment-334234022

If that's the case, share the branch for bounty hunters to have a starting point.

**Comment by LeaTex** [comment] 2017-10-21 16:54
@StarbuckBG where will you get the 250+50 BTG? If you fork the BTC blockchain, you need that amount in BTC today.

**Comment by StarbuckBG** [comment] 2017-10-21 16:55
No. When the fork happens and wallet is available you will be paid.

**Comment by LeaTex** [comment] 2017-10-21 17:09
paid whit BTG? ok, where do you get it? you need to make a transaction to my wallet. and the inputs came from another wallet. these 250+50 can not "appear magically", thay need to exists in the BTG blockchain.

**Comment by StarbuckBG** [comment] 2017-10-21 17:11
They will be paid as soon as the network is started. 
Having your name and eventually your commit will be proof that you have completed the issue. We will add the transaction to the ticket on closing it as a proof that we have paid to you.

**Comment by LeaTex** [comment] 2017-10-21 17:18
I think you are not answering my question.
Where will you get 250+50 BTG to pay me?

**Comment by StarbuckBG** [comment] 2017-10-21 17:44
There is a premining with time locked funs for the next 3 years.
Most of the funds are for development and dev bounties.

**Comment by LeaTex** [comment] 2017-10-21 17:47
ok, thanks for your answer.

**Comment by notf0und** [comment] 2017-10-22 05:41
Then, if I solve this I will be payed with 250 BTG locked for the next 3 years? Sounds great!

**Comment by StarbuckBG** [comment] 2017-10-22 05:55
If you solve it, you get the 250 BTG after the mainnet is started.

**Comment by EliasZ** [comment] 2017-10-22 08:21
So the premine is not time locked after all? Because otherwise you would need 250 BTC right now.

**Comment by StarbuckBG** [comment] 2017-10-22 08:33
75% of the premine is locked for the next 3 year. 
25% are released on launch to support the dev bounties and the need of servers, infrastructure etc.

**Comment by sammy007** [comment] 2017-10-22 09:11
Just cherry-pick it from bitcoin-abc what a problem.

**Comment by krtschmr** [comment] 2017-10-22 09:18
200k premine, that's lots of bounty hunting :>

**Comment by andre-amorim** [comment] 2017-10-22 09:33
Replay protection has todo with time()
Note that's GNU specific. date +%s%6N for microseconds.

**Comment by cryptosi** [comment] 2017-10-22 21:22
Maybe change to "will"

![image](https://user-images.githubusercontent.com/9975784/31866450-e30c4320-b77f-11e7-86c9-84a64fd29914.png)

**Comment by leto** [comment] 2017-10-22 21:34
mainnet will not launch without 2way replay protection, it's cooking, so `is implementing` is better

**Comment by stefek99** [comment] 2017-10-22 21:49
Bounty for a critical feature opened 4 days before the planned fork.

What could possibly go wrong?

😇

**Comment by Ashrafnet** [comment] 2017-10-23 06:53
I don't think you guys going to lunch the fork on time, this 2 way replay protection must be done before lunch.
I think the whole project is scam, its goal is just to manipulate the market, and it did the goal!

**Comment by leto** [comment] 2017-10-23 06:57
![not_launch](https://user-images.githubusercontent.com/30298/31875829-b96bbdde-b784-11e7-95a7-95a602da5233.png)

**Comment by StarbuckBG** [comment] 2017-10-23 07:08
If it was scam none of the people will work nonstop for this. 
Moreover the mainnet will be released later than the fork.

**Comment by EliasZ** [comment] 2017-10-23 07:19
What mechanism is used for timelocking the funds?

**Comment by sammy007** [comment] 2017-10-23 08:15
What a scam party, now ZCL/ZEN scammers joined the train.

**Comment by heyrhett** [comment] 2017-10-23 08:26
Hi @sammy007 , nice to see you, were you able to get it to compile yet?

**Comment by krtschmr** [comment] 2017-10-23 08:26
nobody were able. not even the *fix compile errors* commit fixed that shit.

**Comment by krtschmr** [comment] 2017-10-23 08:27
@EliasZ  mechanism is easy to explain. they promise us to keep the funds. 

how dare you questioning this? ;)

**Comment by StarbuckBG** [comment] 2017-10-23 08:27
I have it working on my 2 MacBooks and on eu-node.bitcoingold-official.org <http://eu-node.bitcoingold-official.org/> .

**Comment by heyrhett** [comment] 2017-10-23 08:29
@krtschmr 
cd depends; make ; <wait 30 minutes>
cd ..
./autogen.sh; ./configure --prefix=/home/username/BTCGPU/depends/x86_64-pc-linux-gnu
make

**Comment by 3389** [comment] 2017-10-23 08:35
连重放保护都不会做的垃圾币，傻逼廖翔，自己偷摸挖了这么多币只拿出这点来，下次麻烦多那点钱给搬砖的。

**Comment by heyrhett** [comment] 2017-10-23 08:52
Please review my pull request: https://github.com/BTCGPU/BTCGPU/pull/62

**Comment by sammy007** [comment] 2017-10-23 11:02
@heyrhett 
> were you able to get it to compile yet?

If something smells like shit, you dont have to taste it. (c) FYMIYWF

At least not until there is a functional testnet.

**Comment by ethan-nx** [comment] 2017-10-23 11:41
The code compiles on Arch Linux just fine. Posting a "Replay protection bounty" just a few days before the fork is a bad joke. Seriously, given all the premined coins you reserve for yourself, you could not handle this on time?

If you cannot compile the code, refer to issue #60, don't post it here.

Cheers,
Ethan

**Comment by w0lph** [comment] 2017-10-23 15:53
**This is a scam**. Their website claims replay protection as already implemented.

**Comment by ocminer** [comment] 2017-10-23 16:22
I neither see funds/premine time locking nor replay protection implemented yet, can someone point me to that code ?! It seems I can just mine blocks like on every other (bitcoin-) fork.

**Comment by dsslimshaddy** [comment] 2017-10-23 16:50
What is this ? Killing all the crypto markets! Biggest meme of the century

**Comment by John1231983** [comment] 2017-10-23 17:33
It is scam because this method did not implement but the website noticed that it has implemented. Please remove the feature

**Comment by ileathan** [comment] 2017-10-23 18:29
How much is the bounty? I don't see that information anywhere.

Also why wasnt this posted before? Kinda scammy.... Bounty is probably too low too..

**Comment by GalRogozinski** [comment] 2017-10-23 19:44
Is someone working on implementing replay protection using SIGHASH_FORK?

**Comment by ileathan** [comment] 2017-10-23 20:34
306 blocks to go - scammers.

**Comment by ileathan** [comment] 2017-10-23 20:36
Oh look... 35 blocks to go seconds later - scammers.

**Comment by lucaspelloni2** [comment] 2017-10-23 22:19
any news?

**Comment by ethan-nx** [comment] 2017-10-23 22:22
Since there is no replay protection yet, see #66

**Comment by adhood** [comment] 2017-10-23 22:59
**Bitcoin Gold is not launching today.**

I know they are calling it a "fork", and many people are expecting it to be similar to the Bitcoin Cash fork (where the snapshot and launch occurred simultaneously), but the only thing happening today is they are making a copy of the Bitcoin blockchain for future use with Bitcoin Gold.

Nothing is going live today. You will not be able to mine, send, receive or do anything else with Bitcoin Gold other than trade it on the few exchanges currently supporting it.

See #39 -- The Bitcoin Gold team has advised that the testnet and mainnet have not been coded yet and they will be reopening a bounty ticket soon with details for anyone who wants to create it for them. I'm sure replay protection will be included during the development of Bitcoin Gold and will be ready by launch, but that is not today and I have not seen an ETA for the actual launch.

**Comment by CryptoInvestment** [comment] 2017-10-24 00:18
People did not understand , the team is composed of two men from china , one hardcore dev, you can see it in his pseudo, the other Martin from Bulgaria, he don't laugh!

They have also a man from Colombia!! They are hungry there !
They have also a man from Spain!! Crisis since 2008!

And one strategist from the USA, who today will not admit that the united states have the most concentrated population of strategist !! 

They know what there are doing. They have just what is necessary, the minimal to launch their fork . And their need to launch quickly is understandable.

Replay protection unavailable: It's a bad point ! Really But they have mesured the the risk in term of timing before they do it.  What I don't like is that they launch making the people money at risk.

You all criticized their remaining, but I find it reasonable. when you understand that it's their project 
 and their work that will build a good part of the value of their exit (say half of the value, probably more after,  the other is inherited of bitcoin and people investment) . And if you are so irritated is because you believe in their project...

If they succeed in the next day, I think we could applaud this dream team !

Hey the team ? I have only an ATI Radeon 3600 HD ! When your receive your fat money, please send me 1 btg to thank me for the support so I can mine on one of your pool. I will post my address . We never know.

**Comment by StarbuckBG** [comment] 2017-10-24 00:22
If all the people that has spend that many times in writing all the posts has focused to write just 1 line of code for each sentence of hate, we would have replay protection, unique address format, Lightning network and whatever possible to be done.

**Comment by StarbuckBG** [comment] 2017-10-24 00:25
If you will just stay and hate you can just start a hate chat than spamming the place people are trying to do something. 
I don’t believe to the names of the people, I believe to their actions. It’s is 3.23 AM my time and I’m still working, not sitting to see how I’m going to be hated, I’m working as I believe in the idea.

If the world was full of doers, not with haters we would be all over the universe and creating things that no one has ever though of. 
When you are just staying there hating, you are just waisting you time, than try to create a better place for everyone.

**Comment by CryptoInvestment** [comment] 2017-10-24 00:26
@StarbuckBG  Did you find my post as of hate post ?

**Comment by pocketaces** [comment] 2017-10-24 00:27
I'm glued to this like it's the final episode of Game of Thrones season 8.

**Comment by CryptoInvestment** [comment] 2017-10-24 00:28
@StarbuckBG Because I tried to support!

**Comment by StarbuckBG** [comment] 2017-10-24 00:30
So please, if you have nothing to help us, just not distract us, we’ve got plenty of work.
If you have questions about the development of the project I will be glad to answer all of them.

@CryptoInvestment the way to support us is to give us a helping hand with a code review of the changes, implement 2 lines of code or give useful advice. You judge our team based on their nationality, which is not right at all!

**Comment by krtschmr** [comment] 2017-10-24 00:35
@StarbuckBG we don't hate. we actually liked the GPU idea, it might be the relief from all the ETH hashrate. it's really needed. but, the way you guys communicate with us is a joke. the way you hide the premine and don't talk about it is a joke. i still might throw all my 155 k/sol towards you, but i doubt it every day more.

**Comment by CryptoInvestment** [comment] 2017-10-24 00:36
@StarbuckBG Edited but it's just because I'm not sure that people read it as I wanted to express it.

**Comment by StarbuckBG** [comment] 2017-10-24 00:40
No-one is hiding the premine. It is in the code I speak for it on all of the interviews.
Please check the document listed as roadmap on our site.
Here is a link to the doc, everything is explained in details : https://btcgpu.org/wp-content/uploads/2017/10/BitcoinGold-Roadmap.pdf <https://btcgpu.org/wp-content/uploads/2017/10/BitcoinGold-Roadmap.pdf>
If you need information just ask me, really we need people to help us at the moment to provide this solution. We are not celebrities in the blockchain development, neither gurus, we are just people who wants to have a way to use all of the bitcoin innovations and add to them non-ASIC PoW :/

**Comment by ICPPDS** [comment] 2017-10-24 00:52
@StarbuckBG I'm not picking a fight but replay protection is a deal breaker, a must have, a critical function. It puts everyone at ease, increases trust and mitigates risk, yet its been left for the last minute.
I know you are asking for people to contribute, I'm not a coder so I can't offer my help, however you need to learn how to better handle criticisms and not think everyone is out to hate you.

In this instance, you guys left a pretty big deal for very late in the game - but you sure as heck have had it on the website for as long as the website exists yet you only posted the bounty and request 3 days ago?  SURELY you can see the error in that and that this should have been something that was thought about in July, not 3 days before the fork.

//just my 2 cents

**Comment by CryptoInvestment** [comment] 2017-10-24 00:56
@StarbuckBG You say help but If you created a small fund for small bounty 1,13,10,20 btg. You will have a lot of helper. There is no helper when you are you are so closed and you are premining. If there are no money or the coin is already launched then we are opensource minded. Otherwise no !  4 block left Good Luck !!!

**Comment by StarbuckBG** [comment] 2017-10-24 00:57
@ICPPDS You are absolutely correct. I came into this project just 2 weeks ago and at that time the date was fixed. Once you have made a statement you shall not change it. Hence I do all my best and I will keep up doing all my best until the moment the main net is stable, secure and functional. This project is the first non-ASIC PoW fork of bitcoin that is actually getting famous and is going to be in that many exchanges. This is a large chance for all of the people who want the bitcoin to be mined again with GPU. I believe in that idea and we are really close to make it real.

**Comment by ICPPDS** [comment] 2017-10-24 01:06
@StarbuckBG 

> I did not know that. But thank you for working hard to fix this.

**Comment by heyrhett** [comment] 2017-10-24 01:06
@ICPPDS , what I think people don't realize is the SIGHASH_FORK_ID implementation of replay protection is complicated.  It was implemented on Bitcoin Cash where there is no SegWit.  Bitcoin Gold also has SegWit, so it is different.

The solution I proposed is very simple, very strong, works with SegWit or legacy transactions, and is endorsed by Greg Maxwell (at least the method, he has not reviewed my code).

I am going back to work on a SIGHASH_FORK_ID implementation though, because I think people want that just because it worked well in Bitcoin Cash.

I agree, we want very strong replay protection, audited and reviewed by everyone.  When people say, "just take it from Bitcoin Cash", I think they have not looked at the code.

Here is one of the commits for Bitcoin Cash's SIGHASH_FORK_ID implementation.  Do people really think this is a better option?  Everyone who does, please seriously look at the complexity of this code:
https://github.com/Bitcoin-ABC/bitcoin-abc/commit/e49826c1fcc36e5ae26de0ad4d06e2063a759e73

**Comment by philsong** [comment] 2017-10-24 01:38
interesting

**Comment by robbaltzer** [comment] 2017-10-24 02:07
On it.

**Comment by ileathan** [comment] 2017-10-24 03:12
@heyrhett I hope they pay you well (I see no bounty information). Or I guess you have alot of btc like them or the premine IDK... but by definition this is a scam now that it is trading and the information on their website has been shown to be flat dishonest.

**Comment by John1231983** [comment] 2017-10-24 03:19
:)). Do you receive the BTG,@ileathan. I also think it is the scam because the main feature does not complete but they report on the website that it "has implemented".

**Comment by bit79** [comment] 2017-10-24 07:12
Isn't this called a "forward looking statement"? There should be a disclaimer, something like: "This website and other items we publish, including through social media outlets, may contain forward-looking statements, the achievement or success of which involves risks, uncertainties, and assumptions. If any such risks or uncertainties materialize or if any of the assumptions proves incorrect, the results of Bitcoin Gold could differ materially from the results expressed or implied by the forward-looking statements we make." (copied from Salesforce.com)

**Comment by rfreemobile** [comment] 2017-10-24 07:45
> If all the people that has spend that many times in writing all the posts has focused to write just 1 line of code for each sentence of hate, we would have replay protection, unique address format, Lightning network and

What...?

Do you think this is how development process works, on complex tricky distributed crypto projects?

![](https://kek.gg/i/4SNyfM.jpeg)

**Comment by tomywomy** [comment] 2017-10-24 11:14
`for i = 1 to 1000;`

^ can I get 1/250th of the bounty for my one line of code?

**Comment by heyrhett** [comment] 2017-10-24 11:17
Closed my pull request as it did not provide adequate replay protection.

Bitcoin blocks do not currently enforce that a tx version number must be > 0, even though the mempool will reject txns with versions less than 0.

An attacker could therefore mine a block on bitcoin with a txn that has a negative version number, so the simple method implemented in my pull request is not adequate and I closed the pull request. 

I believe a SIGHASH_FORKID method is the best approach, though it will require careful review and testing.

**Comment by AlexanderPoschenrieder** [comment] 2017-10-24 12:15
So there's no one working on this right now?

**Comment by 1hiro** [comment] 2017-10-24 12:26
Why would anybody be working on this now?  The scam is over.  The bitcoin gold site is down.  Money was made speculating on btc gaining against the alts before the forking block and the alts getting their value back after the forking block.

**Comment by AlexanderPoschenrieder** [comment] 2017-10-24 12:35
Well, first of all, im bored at work, that's why i asked. 
But most important is because if the wallet and the mainnet are released without Replay protection, and this is a scam, people could rob BTCs just asking some BTG. Which is much worse than just price speculation.

**Comment by StarbuckBG** [comment] 2017-10-24 12:39
As you are bored at work you should have read that the fork is not release. 
a SNAPSHOT has been taken. As soon as the main net is secured with replay protection and unique address format, the main net will be release. Now get back to work, someone is paying you doing something useful (:

**Comment by nisenbaum** [comment] 2017-10-24 14:18
Your project has devs savvy enough to change PoW algo and to premine, but not to code replay protection?! What gives? You knew the replay protection is a MUST, knew it before any other decisions about the alt coin were made. Please explain.

**Comment by jb55** [comment] 2017-10-24 15:51
@nisenbaum protip: it's a scam. carry on.

**Comment by AlexanderPoschenrieder** [comment] 2017-10-24 15:57
@StarbuckBG I know that the fork is not yet released that was i asked if someone was working on this.

**Comment by StarbuckBG** [comment] 2017-10-24 16:03
I’m working on the testnet, you can check my PR. 
H4x is working on small tasks and here is the replay protection. If it is not implemented in 2 days I will implement it.

**Comment by nisenbaum** [comment] 2017-10-24 16:12
@jb55 - Let's not be so judgmental. :) Can we call it "ForkDrop"TM? Innovation sometimes hides in the most unlikely places. I liken this to bacteria in the early moments of life on earth. Endless copying and reproducing, rapid decay and occasional viable mutation. There is a downside of course, as the name of bitcoin gets purposely attached to an alt coin, but that's a price of open source freedom.

**Comment by lmlsna** [comment] 2017-10-24 18:56
😂

**Comment by Riocloud** [comment] 2017-10-25 00:30
Ok, I am working on this part, we can share our code, this is only a small part of the code

**Comment by BTCGReplayUS** [comment] 2017-10-25 03:12
Please see the pull request at https://github.com/BTCGPU/BTCGPU/pull/83.   

This should be the completion of this bounty.   Without a running node system some of the automated tests might fail, but the entire implementation is there and very likely correct: 

DISCLAIMER: Should you choose to use it: none of this code has any warrantee, express or implied, usability for a particular purpose,etc [blah blah](https://en.wikipedia.org/wiki/MIT_License)

The pull request also fixes the vast majority of the warnings reported in https://github.com/BTCGPU/BTCGPU/issues/47

The task includes updating the test suite to use SIGHASH_FORKID, is clear and readable code, and the task is finished before 25.10.2017 12:00 UTC.  

Please review and let me know how to recieve the 300 BTG.  We can make arrangements via PM.

**Comment by jl777** [comment] 2017-10-25 08:06
I was the one that came up with the idea initially for the SIGHASH_FORKID

https://steemit.com/bitcoin/@jl777/bitcoin-spinoff-fork-how-to-make-a-clean-fork-without-any-replay-attack-and-no-blockchain-visible-changes

Just make sure to use a different forkid and also different default ports will simplify people running both BTC and BTG at the same time.

Let me know if you need help

**Comment by alexeyvip** [comment] 2017-10-25 10:24
Is BTG developers don't know how do it? o_O

**Comment by StarbuckBG** [comment] 2017-10-25 10:32
We have too much work to do that and we need more devs in the team.

**Comment by darorl89** [comment] 2017-10-25 14:25
Parody shit coin, take this coin and throw to the dumpster :)

**Comment by flufy3d** [comment] 2017-10-25 15:05
too shame on BTG team.hope the BTC core dev team will help you secretly.

**Comment by cjsin** [comment] 2017-10-25 17:29
Any possibility one of the devs who understands the tech can comment on whether the following strategy would work for splitting coins currently in an exchange (or a local wallet) into a separate wallet only for BTG? I am a newbie to cryptocurrencies but this seems to me to be a valid strategy for avoiding the whole replay issue altogether:

- Before or after Oct 25 / block  491407

1. if you don't have a local wallet, create one with a client such as electrum (or, other people seem to be suggesting coinomi?). give it a name something like for example  "pre_fork_wallet"

2. withdraw BTC from any exchanges into an address from your 'pre_fork_wallet'  local wallet file

- After Oct 25 / block  491407,   but *BEFORE* Nov 1 

3. create a copy of the pre_fork_wallet, give it a new name, like "btg_wallet". This will be the BTG wallet after the BTG network launches on Nov 1. (The addresses in this wallet had BTC associated with them at the time of the fork, and will have BTG associated with them when the new network is operating).

3. create a new local wallet file, naming it something like "btc_wallet". (This will be your BTC wallet which will contain addresses with BTC only and which do not have any BTG associated).

4. open pre_fork_wallet, and btc_wallet 

5. use your local client to perform transactions/transfers to transfer all BTC from the addresses in pre_fork_wallet, to new address(es) in the new "btc_wallet" wallet.

6. now you can use 'btc_wallet' for BTC transactions, without concern for using them on the wrong network. (The addresses in this wallet never existed on the BTG blockchain because this wallet was created after the snapshot, and your BTC balances were transferred to these addresses only after the snapshot, and before the BTG network was operating).

- After the BTG network launches (approx Nov 1)

7. use 'btg_wallet' (or address/private-key combinations exported from it) with a (new?) client that supports BTG,  for BTG transactions only. (The addresses in this wallet were those which had a balance associated at the time of the blockchain snapshort/fork, and hence have a BTG balance after the new network launched.

Does this sound reasonable? Any mistakes in the suggested strategy above?

**Comment by bit79** [comment] 2017-10-25 17:32
You don't need a copy of the wallet - just keep the private key of your address at step 2. After block 491407, move your bitcoins to another address and never reuse the address of step 2. When (if) BTG releases a wallet, import that private key of step 2.

**Comment by cjsin** [comment] 2017-10-25 17:37
yeah I thought that was likely the case however as I'm not aware of the binary format for the wallet files of any of the clients, I thought it's possible they might store cached balances and such in a binary format, so  after the transfer from one wallet to another, the client might think the wallet is empty unless it is a full node that checks the actual blockchain? So thought it safest to just take a copy before the transfer.  But yeah that would be unnecessary if the addresses/keys are being imported into a new btg-supporting client app anyway.  I'll edit the above to add that simplification.

**Comment by notmike-5** [comment] 2017-10-25 20:25
@cjsin

Let's call your 'pre_fork_wallet' X and your 'btc_wallet' Y. What we want to do is transfer value X->Y in such a way that no attacker can rebroadcast a valid transaction from one chain onto another and steal (or strand) our value on the other chain. We call this 'replay protection.'

In the example you gave, value is transferred X->Y and Y->Z, where X and Y are locally controlled wallets and Z may be controlled by a third-party (like an exchange). Your assumption is that, because addresses in Y have not existed on the BTG blockchain, that this protocol would provide replay protection. However, an attacker who rebroadcasts the valid transaction X->Y on the other chain creates those addresses on that chain. By itself, this is a mere inconvenience. One could use their seed to recreate Y later in a client and regain their value. However, a valid transaction Y->Z that were rebroadcast, where Z is third-party controlled, runs a real risk of stranding value or facilitating its theft.

For this reason, your protocol does not provide replay protection.

**Comment by ileathan** [comment] 2017-10-29 03:22
"If all the people that has spend that many times in writing all the posts has focused to write just 1 line of code for each sentence of hate, we would have replay protection, unique address format, Lightning network and whatever possible to be done."

ROFL? - You posted a public bounty FOR REPLAY PROTECTION 4 days before launch...

 @StarbuckBG your a COMPLETE scammer, how about I copy paste Bitcoin and replace core with Gold and then premine 200k coins, how about then I help? ..... Just wow...

Please go read the definition of the word scammer, and then BitcoinGolds website. Please.

**Comment by ileathan** [comment] 2017-10-29 03:24
Total scam.

**Comment by ileathan** [comment] 2017-10-29 03:32
@jl777 I guess you have the btc so i understand your help, but they are by definition scamming and have continued to scam for many weeks now. If you actually help them, tell them to atleast make some sort of apology, I wanted to keep my BTG but i was forced to sell out when I saw a public bounty like that on github, total clowns.

I mean am I the only one who noticed (BTG) Bitgem was the better buy of this btc gold scam...

**Comment by mjoh090** [comment] 2017-10-29 04:36
@ileathan I think it is more the case of ambition exceeding ability. While the launch of this project has been shambolic, the engagement at times with the community is abysmal. 

I was on the slack channel before, and the question was asked about when BTG will be added to the Bittrex Exchange. Someone said "Never" at which point the founder Jack Liao jumps in with following response: 

" suppprt or not, its up to exchange.but they need to give btg to their client.this is bottom" 

I know English is not his first language, but there is still an astonishing lack of care in his response. 

He was provided with context and therefore with opportunity to remind the community of the particular issues prohibiting uptake by Bittrex and the other major Exchanges, and how they were addressing those issues to win their confidence and encourage future uptake by those major Exchanges. Instead he writes something tonally belligerent that borders on unintelligible. 

For such a high profile new coin release, the seeming lack of organisation (Martin indicated elsewhere that he hardly communicates with Jack) and professionalism of the team behind this coin is surprising, and alarming.

**Comment by ileathan** [comment] 2017-10-29 19:04
I hope your right, I often come back to my posts after some years and feel like an asshole. But the point is they are offering a bounty in BTG for replay protection when they already sold BTG as having replay protection..

**Comment by BTCGReplayUS** [comment] 2017-10-30 16:49
I wanted to write here (and on the PR page) to confirm that with the code implemented and the bounty completed, the BTG team has followed through with payment of the bounty in full, on time, in the manner that I preferred.  This instills a significant amount of faith (to me) that the project is being run by people who have a deep sense of professionalism, and I am grateful to them for the opportunity.

Thank you very much.

**Comment by mchybo** [comment] 2017-10-30 23:06
@BTCGReplayUS - then why is this issue still open?

**Comment by mjoh090** [comment] 2017-10-30 23:30
@BTCGReplayUS Thanks for the update, and congratulations on your windfall.

 I for one never doubted that they would follow through on paying the bounty, it would have 'lights-out' if they didn't. 

Your comment's inclusion of 'to me' qualifies your graciousness and gratitude with an awareness that this payment in reality does not invalidate persistent concerns for the rest of us, and therefore does not diminish the need for continued vigilance.

**Comment by darxis** [comment] 2017-11-01 09:33
#109 Close?

**Comment by h4x3rotab** [comment] 2017-11-01 09:34
Sure.

**Closed by h4x3rotab** 2017-11-01 09:34 UTC
Labels: bounty

**Comment by ileathan** [comment] 2017-11-04 23:58
@John1231983 yes I did, well in profit ;)

@bit79 It changes nothing, but no "has implemented" is not a forward looking statement. Not whatsoever. 

Paying that implementation due to the implementation is a bit of a stretch.
