### ISSUE TITLE
Regtest network bug with wrong values in K,N

### ISSUE THREAD

**Issue by evgenyundefined** [BTCGPU/BTCGPU#76] opened 2017-10-24 16:53 UTC
Regtest network have init K and N params different from mainnet and testnet. 
On mainnet and testnet K, N
        const size_t N = 200, K = 9;  // Same as mainchain.
        BOOST_STATIC_ASSERT(equihash_parameters_acceptable(N, K));
        nEquihashN = N;
        nEquihashK = K;
On regtest K, N (chainparams.cpp:344)
        const size_t N = 48, K = 5;
        BOOST_STATIC_ASSERT(equihash_parameters_acceptable(N, K));
        nEquihashN = N;
        nEquihashK = K;

With public miners on mainnet and testnet all works fine, but if you make regtest network (for some test) daemon reject all shares from public miners. (this problem have all forks of zerocash). 

Please make regtest params same mainnet and make genesis block for regtest with K,N 200,9 and not with K,N 48,5

**Comment by StarbuckBG** [comment] 2017-10-24 16:57
Will check that thanks !

**Comment by evgenyundefined** [comment] 2017-10-24 17:22
thanks, this bug in chainparams.cpp:344 for fix this in zcash i copy genesis block from testnet and change K,N and make some magic for make working private testnet)

**Comment by h4x3rotab** [comment] 2017-10-25 08:01
IMHO parameters (48,5) are intendedly chosen for regtest mode, which is only for local regression tests. So it's not designed to talk with mainnet and testnet clients. Larger numbers will slow down the test duration.

Please correct me if I'm wrong.

**Comment by StarbuckBG** [comment] 2017-10-25 10:48
@evgenyundefined please review the statement of @h4x3rotab. I agree with him.

**Comment by evgenyundefined** [comment] 2017-10-25 10:51
Regtest network starts from low difficulty and no have problems with test duration. Ok can agree with him, but for pool developers this actual problem. I continue use my solution with some magic of testnet genesis block.

**Comment by h4x3rotab** [comment] 2017-10-31 17:47
Testnet is on the way. I'm going to close this issue.

**Closed by h4x3rotab** 2017-10-31 17:47 UTC

**Comment by oliverw** [comment] 2017-11-21 18:00
@evgenyundefined Any chance for sharing your updated chainparams.cpp?

**Comment by evgenyundefined** [comment] 2017-11-21 18:43
@oliverw i not make chainparams for bgold, i at first time see this problem on zcash and make only for zcash if you need modificated sources of zcash with working regtest on kn same on mainnet write for me (zuenko@gmail.com)

**Comment by marcofortina** [comment] 2017-12-13 23:48
@evgenyundefined I have the same problem. I'd like to generate the regtest genesis block that include a valid equihash solution inside the block but I'm not able to find a easy solution for this. Coudl you help me please?
